-- wtech.md production schema for Supabase.
-- Run once in Supabase SQL Editor. It is idempotent.

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  kind text not null check (kind in ('contact', 'call', 'audit', 'chat')),
  locale text not null check (locale in ('ro', 'ru', 'en')),
  name text,
  phone text,
  email text,
  company text,
  message text,
  interest text,
  url text,
  ip text not null,
  delivered boolean not null default false,
  delivered_at timestamptz,
  handled boolean not null default false
);

create index if not exists leads_created_idx on public.leads (created_at desc);
create index if not exists leads_open_idx on public.leads (handled, created_at desc);

create table if not exists public.settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.rate_limits (
  key text primary key,
  window_started_at timestamptz not null default now(),
  hits integer not null default 1 check (hits > 0)
);

alter table public.leads enable row level security;
alter table public.settings enable row level security;
alter table public.rate_limits enable row level security;

-- No anon/authenticated policies are created. The browser cannot read or write these tables.
-- Only the server-side service role key used by Vercel bypasses RLS.
revoke all on public.leads from anon, authenticated;
revoke all on public.settings from anon, authenticated;
revoke all on public.rate_limits from anon, authenticated;

create or replace function public.consume_rate_limit(
  p_key text,
  p_limit integer,
  p_window_seconds integer
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  now_at timestamptz := clock_timestamp();
  started_at timestamptz;
  current_hits integer;
begin
  if p_key is null or length(p_key) > 300 or p_limit < 1 or p_window_seconds < 1 then
    raise exception 'invalid rate limit input';
  end if;

  insert into public.rate_limits as existing (key, window_started_at, hits)
  values (p_key, now_at, 1)
  on conflict (key) do update set
    window_started_at = case
      when existing.window_started_at <= now_at - make_interval(secs => p_window_seconds) then now_at
      else existing.window_started_at
    end,
    hits = case
      when existing.window_started_at <= now_at - make_interval(secs => p_window_seconds) then 1
      else existing.hits + 1
    end
  returning window_started_at, hits into started_at, current_hits;

  if current_hits > p_limit then
    return greatest(1, ceil(extract(epoch from (started_at + make_interval(secs => p_window_seconds) - now_at)))::integer);
  end if;
  return 0;
end;
$$;

revoke all on function public.consume_rate_limit(text, integer, integer) from public, anon, authenticated;
grant execute on function public.consume_rate_limit(text, integer, integer) to service_role;

-- Keep the small rate-limit table tidy. This can be scheduled daily with Supabase Cron later.
create or replace function public.prune_rate_limits()
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.rate_limits where window_started_at < now() - interval '24 hours';
$$;

revoke all on function public.prune_rate_limits() from public, anon, authenticated;
grant execute on function public.prune_rate_limits() to service_role;
